### ISSUE TITLE
Does it work on a Raspberry Pi? 

### ISSUE THREAD

**Issue by gdebroux** [dst6se/aquatemp#3]
Dear, I'm trying to get the script working on a Rasp Pi, however I'm getting errors when deploying it.

pi@smapi:~/heatpump/aquatemp-main $ systemctl status aquatemp_status
* aquatemp_status.service - Heatpump_control
   Loaded: loaded (/lib/systemd/system/aquatemp_status.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-05-05 13:06:33 CEST; 26s ago
 Main PID: 3047 (status.sh)
    Tasks: 2 (limit: 3717)
   CGroup: /system.slice/aquatemp_status.service
           |-3047 /bin/bash /home/pi/heatpump/aquatemp-main/status.sh
           `-3582 sleep 20

May 05 13:06:55 smapi status.sh[3047]: Warning: Unable to locate configuration directory, default config not loaded.
May 05 13:06:55 smapi status.sh[3047]: Warning: Unable to locate configuration directory, default config not loaded.
May 05 13:06:55 smapi status.sh[3047]: /home/pi/heatpump/aquatemp-main/heatpump: line 207: [: =: unary operator expected
May 05 13:06:55 smapi status.sh[3047]: /home/pi/heatpump/aquatemp-main/heatpump: line 211: [: =: unary operator expected
May 05 13:06:55 smapi status.sh[3047]: /home/pi/heatpump/aquatemp-main/heatpump: line 216: [: =: unary operator expected
May 05 13:06:55 smapi status.sh[3047]: /home/pi/heatpump/aquatemp-main/heatpump: line 220: [: =: unary operator expected
May 05 13:06:55 smapi status.sh[3047]: /home/pi/heatpump/aquatemp-main/heatpump: line 140: [: =: unary operator expected
May 05 13:06:55 smapi status.sh[3047]: /home/pi/heatpump/aquatemp-main/heatpump: line 150: [: =: unary operator expected
May 05 13:06:55 smapi status.sh[3047]: Warning: Unable to locate configuration directory, default config not loaded.
May 05 13:06:55 smapi status.sh[3047]: Warning: Unable to locate configuration directory, default config not loaded.

Thanks for your thoughts.

**Comment by gdebroux** [comment]
All sorted. Seems that the "[: =: unary operator expected" error needs double [[ and ]] on a Rasp Pi.
And the default config not loaded is also resolved by adding the settings directly within the "heat pump" script.

**Comment by gdebroux** [comment]
Thanks for the nice script :-)

**Comment by dst6se** [comment]
Nice you sorted everything out ! 
I have never tried the scipt under Ubuntu !


Thanks


Danne

**Comment by dst6se** [comment]
I have updated the script with [[ , but i have no problem to read the settingsfile from rasbian !
